all: Run1 2Run 3Run
Run1: binary_tree.cpp
	g++ -o Run1 binary_tree.cpp
2Run: bfs_tree.cpp
	g++ -o 2Run bfs_tree.cpp

3Run: dfs_tree.cpp
	g++ -o 3Run dfs_tree.cpp -std=c++11
clean:
	rm  Run1 2Run 3Run
