include make.common

#Getdata.o : Getdata.cpp Getdata.h
#		g++ -c -O Getdata.cpp

#cfmfinal.o : cfmfinal.cpp Getdata.h
#		g++ -c -O cfmfinal.cpp
#
#cfmfinal : Getdata.o cfmfinal.o

#		g++ -O -o cfmfinal Getdata.o cfmfinal.o 
